# Generated by Django 5.0.1 on 2024-02-01 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Open'), (2, 'Issued'), (3, 'Completed'), (4, 'Closed')])),
                ('orderer', models.CharField(max_length=100)),
                ('preparer', models.CharField(max_length=100)),
                ('order_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinner.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinner.order')),
            ],
        ),
    ]
