# Generated by Django 5.0.1 on 2024-02-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_alter_order_complete_time_alter_order_preparer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Issued'), (3, 'Completed'), (4, 'Closed'), (5, 'Cancelled')]),
        ),
    ]
